// Every country except Israel. Generated list of dialling codes.
export type Country = {
  code: string;
  dial: string;
  flag: string;
  en: string;
  ar: string;
};

export const COUNTRIES: Country[] = [
  { code: "AF", dial: "+93", flag: "🇦🇫", en: "Afghanistan", ar: "أفغانستان" },
  { code: "AL", dial: "+355", flag: "🇦🇱", en: "Albania", ar: "ألبانيا" },
  { code: "DZ", dial: "+213", flag: "🇩🇿", en: "Algeria", ar: "الجزائر" },
  { code: "AD", dial: "+376", flag: "🇦🇩", en: "Andorra", ar: "أندورا" },
  { code: "AO", dial: "+244", flag: "🇦🇴", en: "Angola", ar: "أنغولا" },
  { code: "AG", dial: "+1268", flag: "🇦🇬", en: "Antigua & Barbuda", ar: "أنتيغوا وبربودا" },
  { code: "AR", dial: "+54", flag: "🇦🇷", en: "Argentina", ar: "الأرجنتين" },
  { code: "AM", dial: "+374", flag: "🇦🇲", en: "Armenia", ar: "أرمينيا" },
  { code: "AU", dial: "+61", flag: "🇦🇺", en: "Australia", ar: "أستراليا" },
  { code: "AT", dial: "+43", flag: "🇦🇹", en: "Austria", ar: "النمسا" },
  { code: "AZ", dial: "+994", flag: "🇦🇿", en: "Azerbaijan", ar: "أذربيجان" },
  { code: "BS", dial: "+1242", flag: "🇧🇸", en: "Bahamas", ar: "جزر البهاما" },
  { code: "BH", dial: "+973", flag: "🇧🇭", en: "Bahrain", ar: "البحرين" },
  { code: "BD", dial: "+880", flag: "🇧🇩", en: "Bangladesh", ar: "بنغلاديش" },
  { code: "BB", dial: "+1246", flag: "🇧🇧", en: "Barbados", ar: "بربادوس" },
  { code: "BY", dial: "+375", flag: "🇧🇾", en: "Belarus", ar: "بيلاروس" },
  { code: "BE", dial: "+32", flag: "🇧🇪", en: "Belgium", ar: "بلجيكا" },
  { code: "BZ", dial: "+501", flag: "🇧🇿", en: "Belize", ar: "بليز" },
  { code: "BJ", dial: "+229", flag: "🇧🇯", en: "Benin", ar: "بنين" },
  { code: "BT", dial: "+975", flag: "🇧🇹", en: "Bhutan", ar: "بوتان" },
  { code: "BO", dial: "+591", flag: "🇧🇴", en: "Bolivia", ar: "بوليفيا" },
  { code: "BA", dial: "+387", flag: "🇧🇦", en: "Bosnia & Herzegovina", ar: "البوسنة والهرسك" },
  { code: "BW", dial: "+267", flag: "🇧🇼", en: "Botswana", ar: "بوتسوانا" },
  { code: "BR", dial: "+55", flag: "🇧🇷", en: "Brazil", ar: "البرازيل" },
  { code: "BN", dial: "+673", flag: "🇧🇳", en: "Brunei", ar: "بروناي" },
  { code: "BG", dial: "+359", flag: "🇧🇬", en: "Bulgaria", ar: "بلغاريا" },
  { code: "BF", dial: "+226", flag: "🇧🇫", en: "Burkina Faso", ar: "بوركينا فاسو" },
  { code: "BI", dial: "+257", flag: "🇧🇮", en: "Burundi", ar: "بوروندي" },
  { code: "KH", dial: "+855", flag: "🇰🇭", en: "Cambodia", ar: "كمبوديا" },
  { code: "CM", dial: "+237", flag: "🇨🇲", en: "Cameroon", ar: "الكاميرون" },
  { code: "CA", dial: "+1", flag: "🇨🇦", en: "Canada", ar: "كندا" },
  { code: "CV", dial: "+238", flag: "🇨🇻", en: "Cape Verde", ar: "الرأس الأخضر" },
  { code: "CF", dial: "+236", flag: "🇨🇫", en: "Central African Republic", ar: "جمهورية أفريقيا الوسطى" },
  { code: "TD", dial: "+235", flag: "🇹🇩", en: "Chad", ar: "تشاد" },
  { code: "CL", dial: "+56", flag: "🇨🇱", en: "Chile", ar: "تشيلي" },
  { code: "CN", dial: "+86", flag: "🇨🇳", en: "China", ar: "الصين" },
  { code: "CO", dial: "+57", flag: "🇨🇴", en: "Colombia", ar: "كولومبيا" },
  { code: "KM", dial: "+269", flag: "🇰🇲", en: "Comoros", ar: "جزر القمر" },
  { code: "CG", dial: "+242", flag: "🇨🇬", en: "Congo - Brazzaville", ar: "الكونغو - برازافيل" },
  { code: "CD", dial: "+243", flag: "🇨🇩", en: "Congo - Kinshasa", ar: "الكونغو - كينشاسا" },
  { code: "CR", dial: "+506", flag: "🇨🇷", en: "Costa Rica", ar: "كوستاريكا" },
  { code: "CI", dial: "+225", flag: "🇨🇮", en: "Côte d’Ivoire", ar: "ساحل العاج" },
  { code: "HR", dial: "+385", flag: "🇭🇷", en: "Croatia", ar: "كرواتيا" },
  { code: "CU", dial: "+53", flag: "🇨🇺", en: "Cuba", ar: "كوبا" },
  { code: "CY", dial: "+357", flag: "🇨🇾", en: "Cyprus", ar: "قبرص" },
  { code: "CZ", dial: "+420", flag: "🇨🇿", en: "Czechia", ar: "التشيك" },
  { code: "DK", dial: "+45", flag: "🇩🇰", en: "Denmark", ar: "الدانمرك" },
  { code: "DJ", dial: "+253", flag: "🇩🇯", en: "Djibouti", ar: "جيبوتي" },
  { code: "DM", dial: "+1767", flag: "🇩🇲", en: "Dominica", ar: "دومينيكا" },
  { code: "DO", dial: "+1809", flag: "🇩🇴", en: "Dominican Republic", ar: "جمهورية الدومينيكان" },
  { code: "EC", dial: "+593", flag: "🇪🇨", en: "Ecuador", ar: "الإكوادور" },
  { code: "EG", dial: "+20", flag: "🇪🇬", en: "Egypt", ar: "مصر" },
  { code: "SV", dial: "+503", flag: "🇸🇻", en: "El Salvador", ar: "السلفادور" },
  { code: "GQ", dial: "+240", flag: "🇬🇶", en: "Equatorial Guinea", ar: "غينيا الاستوائية" },
  { code: "ER", dial: "+291", flag: "🇪🇷", en: "Eritrea", ar: "إريتريا" },
  { code: "EE", dial: "+372", flag: "🇪🇪", en: "Estonia", ar: "إستونيا" },
  { code: "SZ", dial: "+268", flag: "🇸🇿", en: "Eswatini", ar: "إسواتيني" },
  { code: "ET", dial: "+251", flag: "🇪🇹", en: "Ethiopia", ar: "إثيوبيا" },
  { code: "FO", dial: "+298", flag: "🇫🇴", en: "Faroe Islands", ar: "جزر فارو" },
  { code: "FJ", dial: "+679", flag: "🇫🇯", en: "Fiji", ar: "فيجي" },
  { code: "FI", dial: "+358", flag: "🇫🇮", en: "Finland", ar: "فنلندا" },
  { code: "FR", dial: "+33", flag: "🇫🇷", en: "France", ar: "فرنسا" },
  { code: "GA", dial: "+241", flag: "🇬🇦", en: "Gabon", ar: "الغابون" },
  { code: "GM", dial: "+220", flag: "🇬🇲", en: "Gambia", ar: "غامبيا" },
  { code: "GE", dial: "+995", flag: "🇬🇪", en: "Georgia", ar: "جورجيا" },
  { code: "DE", dial: "+49", flag: "🇩🇪", en: "Germany", ar: "ألمانيا" },
  { code: "GH", dial: "+233", flag: "🇬🇭", en: "Ghana", ar: "غانا" },
  { code: "GI", dial: "+350", flag: "🇬🇮", en: "Gibraltar", ar: "جبل طارق" },
  { code: "GR", dial: "+30", flag: "🇬🇷", en: "Greece", ar: "اليونان" },
  { code: "GL", dial: "+299", flag: "🇬🇱", en: "Greenland", ar: "غرينلاند" },
  { code: "GD", dial: "+1473", flag: "🇬🇩", en: "Grenada", ar: "غرينادا" },
  { code: "GT", dial: "+502", flag: "🇬🇹", en: "Guatemala", ar: "غواتيمالا" },
  { code: "GN", dial: "+224", flag: "🇬🇳", en: "Guinea", ar: "غينيا" },
  { code: "GW", dial: "+245", flag: "🇬🇼", en: "Guinea-Bissau", ar: "غينيا بيساو" },
  { code: "GY", dial: "+592", flag: "🇬🇾", en: "Guyana", ar: "غيانا" },
  { code: "HT", dial: "+509", flag: "🇭🇹", en: "Haiti", ar: "هايتي" },
  { code: "HN", dial: "+504", flag: "🇭🇳", en: "Honduras", ar: "هندوراس" },
  { code: "HK", dial: "+852", flag: "🇭🇰", en: "Hong Kong SAR China", ar: "هونغ كونغ الصينية (منطقة إدارية خاصة)" },
  { code: "HU", dial: "+36", flag: "🇭🇺", en: "Hungary", ar: "هنغاريا" },
  { code: "IS", dial: "+354", flag: "🇮🇸", en: "Iceland", ar: "آيسلندا" },
  { code: "IN", dial: "+91", flag: "🇮🇳", en: "India", ar: "الهند" },
  { code: "ID", dial: "+62", flag: "🇮🇩", en: "Indonesia", ar: "إندونيسيا" },
  { code: "IR", dial: "+98", flag: "🇮🇷", en: "Iran", ar: "إيران" },
  { code: "IQ", dial: "+964", flag: "🇮🇶", en: "Iraq", ar: "العراق" },
  { code: "IE", dial: "+353", flag: "🇮🇪", en: "Ireland", ar: "أيرلندا" },
  { code: "IT", dial: "+39", flag: "🇮🇹", en: "Italy", ar: "إيطاليا" },
  { code: "JM", dial: "+1876", flag: "🇯🇲", en: "Jamaica", ar: "جامايكا" },
  { code: "JP", dial: "+81", flag: "🇯🇵", en: "Japan", ar: "اليابان" },
  { code: "JO", dial: "+962", flag: "🇯🇴", en: "Jordan", ar: "الأردن" },
  { code: "KZ", dial: "+7", flag: "🇰🇿", en: "Kazakhstan", ar: "كازاخستان" },
  { code: "KE", dial: "+254", flag: "🇰🇪", en: "Kenya", ar: "كينيا" },
  { code: "KI", dial: "+686", flag: "🇰🇮", en: "Kiribati", ar: "كيريباتي" },
  { code: "XK", dial: "+383", flag: "🇽🇰", en: "Kosovo", ar: "كوسوفو" },
  { code: "KW", dial: "+965", flag: "🇰🇼", en: "Kuwait", ar: "الكويت" },
  { code: "KG", dial: "+996", flag: "🇰🇬", en: "Kyrgyzstan", ar: "قيرغيزستان" },
  { code: "LA", dial: "+856", flag: "🇱🇦", en: "Laos", ar: "لاوس" },
  { code: "LV", dial: "+371", flag: "🇱🇻", en: "Latvia", ar: "لاتفيا" },
  { code: "LB", dial: "+961", flag: "🇱🇧", en: "Lebanon", ar: "لبنان" },
  { code: "LS", dial: "+266", flag: "🇱🇸", en: "Lesotho", ar: "ليسوتو" },
  { code: "LR", dial: "+231", flag: "🇱🇷", en: "Liberia", ar: "ليبيريا" },
  { code: "LY", dial: "+218", flag: "🇱🇾", en: "Libya", ar: "ليبيا" },
  { code: "LI", dial: "+423", flag: "🇱🇮", en: "Liechtenstein", ar: "ليختنشتاين" },
  { code: "LT", dial: "+370", flag: "🇱🇹", en: "Lithuania", ar: "ليتوانيا" },
  { code: "LU", dial: "+352", flag: "🇱🇺", en: "Luxembourg", ar: "لوكسمبورغ" },
  { code: "MO", dial: "+853", flag: "🇲🇴", en: "Macao SAR China", ar: "منطقة ماكاو الإدارية الخاصة" },
  { code: "MG", dial: "+261", flag: "🇲🇬", en: "Madagascar", ar: "مدغشقر" },
  { code: "MW", dial: "+265", flag: "🇲🇼", en: "Malawi", ar: "ملاوي" },
  { code: "MY", dial: "+60", flag: "🇲🇾", en: "Malaysia", ar: "ماليزيا" },
  { code: "MV", dial: "+960", flag: "🇲🇻", en: "Maldives", ar: "جزر المالديف" },
  { code: "ML", dial: "+223", flag: "🇲🇱", en: "Mali", ar: "مالي" },
  { code: "MT", dial: "+356", flag: "🇲🇹", en: "Malta", ar: "مالطا" },
  { code: "MH", dial: "+692", flag: "🇲🇭", en: "Marshall Islands", ar: "جزر مارشال" },
  { code: "MR", dial: "+222", flag: "🇲🇷", en: "Mauritania", ar: "موريتانيا" },
  { code: "MU", dial: "+230", flag: "🇲🇺", en: "Mauritius", ar: "موريشيوس" },
  { code: "MX", dial: "+52", flag: "🇲🇽", en: "Mexico", ar: "المكسيك" },
  { code: "FM", dial: "+691", flag: "🇫🇲", en: "Micronesia", ar: "ميكرونيزيا" },
  { code: "MD", dial: "+373", flag: "🇲🇩", en: "Moldova", ar: "مولدوفا" },
  { code: "MC", dial: "+377", flag: "🇲🇨", en: "Monaco", ar: "موناكو" },
  { code: "MN", dial: "+976", flag: "🇲🇳", en: "Mongolia", ar: "منغوليا" },
  { code: "ME", dial: "+382", flag: "🇲🇪", en: "Montenegro", ar: "الجبل الأسود" },
  { code: "MA", dial: "+212", flag: "🇲🇦", en: "Morocco", ar: "المغرب" },
  { code: "MZ", dial: "+258", flag: "🇲🇿", en: "Mozambique", ar: "موزمبيق" },
  { code: "MM", dial: "+95", flag: "🇲🇲", en: "Myanmar (Burma)", ar: "ميانمار (بورما)" },
  { code: "NA", dial: "+264", flag: "🇳🇦", en: "Namibia", ar: "ناميبيا" },
  { code: "NR", dial: "+674", flag: "🇳🇷", en: "Nauru", ar: "ناورو" },
  { code: "NP", dial: "+977", flag: "🇳🇵", en: "Nepal", ar: "نيبال" },
  { code: "NL", dial: "+31", flag: "🇳🇱", en: "Netherlands", ar: "هولندا" },
  { code: "NZ", dial: "+64", flag: "🇳🇿", en: "New Zealand", ar: "نيوزيلندا" },
  { code: "NI", dial: "+505", flag: "🇳🇮", en: "Nicaragua", ar: "نيكاراغوا" },
  { code: "NE", dial: "+227", flag: "🇳🇪", en: "Niger", ar: "النيجر" },
  { code: "NG", dial: "+234", flag: "🇳🇬", en: "Nigeria", ar: "نيجيريا" },
  { code: "KP", dial: "+850", flag: "🇰🇵", en: "North Korea", ar: "كوريا الشمالية" },
  { code: "MK", dial: "+389", flag: "🇲🇰", en: "North Macedonia", ar: "مقدونيا الشمالية" },
  { code: "NO", dial: "+47", flag: "🇳🇴", en: "Norway", ar: "النرويج" },
  { code: "OM", dial: "+968", flag: "🇴🇲", en: "Oman", ar: "عُمان" },
  { code: "PK", dial: "+92", flag: "🇵🇰", en: "Pakistan", ar: "باكستان" },
  { code: "PW", dial: "+680", flag: "🇵🇼", en: "Palau", ar: "بالاو" },
  { code: "PS", dial: "+970", flag: "🇵🇸", en: "Palestinian Territories", ar: "الأراضي الفلسطينية" },
  { code: "PA", dial: "+507", flag: "🇵🇦", en: "Panama", ar: "بنما" },
  { code: "PG", dial: "+675", flag: "🇵🇬", en: "Papua New Guinea", ar: "بابوا غينيا الجديدة" },
  { code: "PY", dial: "+595", flag: "🇵🇾", en: "Paraguay", ar: "باراغواي" },
  { code: "PE", dial: "+51", flag: "🇵🇪", en: "Peru", ar: "بيرو" },
  { code: "PH", dial: "+63", flag: "🇵🇭", en: "Philippines", ar: "الفلبين" },
  { code: "PL", dial: "+48", flag: "🇵🇱", en: "Poland", ar: "بولندا" },
  { code: "PT", dial: "+351", flag: "🇵🇹", en: "Portugal", ar: "البرتغال" },
  { code: "PR", dial: "+1787", flag: "🇵🇷", en: "Puerto Rico", ar: "بورتوريكو" },
  { code: "QA", dial: "+974", flag: "🇶🇦", en: "Qatar", ar: "قطر" },
  { code: "RO", dial: "+40", flag: "🇷🇴", en: "Romania", ar: "رومانيا" },
  { code: "RU", dial: "+7", flag: "🇷🇺", en: "Russia", ar: "روسيا" },
  { code: "RW", dial: "+250", flag: "🇷🇼", en: "Rwanda", ar: "رواندا" },
  { code: "WS", dial: "+685", flag: "🇼🇸", en: "Samoa", ar: "ساموا" },
  { code: "SM", dial: "+378", flag: "🇸🇲", en: "San Marino", ar: "سان مارينو" },
  { code: "ST", dial: "+239", flag: "🇸🇹", en: "São Tomé & Príncipe", ar: "ساو تومي وبرينسيبي" },
  { code: "SA", dial: "+966", flag: "🇸🇦", en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
  { code: "SN", dial: "+221", flag: "🇸🇳", en: "Senegal", ar: "السنغال" },
  { code: "RS", dial: "+381", flag: "🇷🇸", en: "Serbia", ar: "صربيا" },
  { code: "SC", dial: "+248", flag: "🇸🇨", en: "Seychelles", ar: "سيشل" },
  { code: "SL", dial: "+232", flag: "🇸🇱", en: "Sierra Leone", ar: "سيراليون" },
  { code: "SG", dial: "+65", flag: "🇸🇬", en: "Singapore", ar: "سنغافورة" },
  { code: "SK", dial: "+421", flag: "🇸🇰", en: "Slovakia", ar: "سلوفاكيا" },
  { code: "SI", dial: "+386", flag: "🇸🇮", en: "Slovenia", ar: "سلوفينيا" },
  { code: "SB", dial: "+677", flag: "🇸🇧", en: "Solomon Islands", ar: "جزر سليمان" },
  { code: "SO", dial: "+252", flag: "🇸🇴", en: "Somalia", ar: "الصومال" },
  { code: "ZA", dial: "+27", flag: "🇿🇦", en: "South Africa", ar: "جنوب أفريقيا" },
  { code: "KR", dial: "+82", flag: "🇰🇷", en: "South Korea", ar: "كوريا الجنوبية" },
  { code: "SS", dial: "+211", flag: "🇸🇸", en: "South Sudan", ar: "جنوب السودان" },
  { code: "ES", dial: "+34", flag: "🇪🇸", en: "Spain", ar: "إسبانيا" },
  { code: "LK", dial: "+94", flag: "🇱🇰", en: "Sri Lanka", ar: "سريلانكا" },
  { code: "KN", dial: "+1869", flag: "🇰🇳", en: "St. Kitts & Nevis", ar: "سانت كيتس ونيفيس" },
  { code: "LC", dial: "+1758", flag: "🇱🇨", en: "St. Lucia", ar: "سانت لوسيا" },
  { code: "VC", dial: "+1784", flag: "🇻🇨", en: "St. Vincent & Grenadines", ar: "سانت فنسنت وجزر غرينادين" },
  { code: "SD", dial: "+249", flag: "🇸🇩", en: "Sudan", ar: "السودان" },
  { code: "SR", dial: "+597", flag: "🇸🇷", en: "Suriname", ar: "سورينام" },
  { code: "SE", dial: "+46", flag: "🇸🇪", en: "Sweden", ar: "السويد" },
  { code: "CH", dial: "+41", flag: "🇨🇭", en: "Switzerland", ar: "سويسرا" },
  { code: "SY", dial: "+963", flag: "🇸🇾", en: "Syria", ar: "سوريا" },
  { code: "TW", dial: "+886", flag: "🇹🇼", en: "Taiwan", ar: "تايوان" },
  { code: "TJ", dial: "+992", flag: "🇹🇯", en: "Tajikistan", ar: "طاجيكستان" },
  { code: "TZ", dial: "+255", flag: "🇹🇿", en: "Tanzania", ar: "تنزانيا" },
  { code: "TH", dial: "+66", flag: "🇹🇭", en: "Thailand", ar: "تايلاند" },
  { code: "TL", dial: "+670", flag: "🇹🇱", en: "Timor-Leste", ar: "تيمور - ليشتي" },
  { code: "TG", dial: "+228", flag: "🇹🇬", en: "Togo", ar: "توغو" },
  { code: "TO", dial: "+676", flag: "🇹🇴", en: "Tonga", ar: "تونغا" },
  { code: "TT", dial: "+1868", flag: "🇹🇹", en: "Trinidad & Tobago", ar: "ترينيداد وتوباغو" },
  { code: "TN", dial: "+216", flag: "🇹🇳", en: "Tunisia", ar: "تونس" },
  { code: "TR", dial: "+90", flag: "🇹🇷", en: "Türkiye", ar: "تركيا" },
  { code: "TM", dial: "+993", flag: "🇹🇲", en: "Turkmenistan", ar: "تركمانستان" },
  { code: "TV", dial: "+688", flag: "🇹🇻", en: "Tuvalu", ar: "توفالو" },
  { code: "UG", dial: "+256", flag: "🇺🇬", en: "Uganda", ar: "أوغندا" },
  { code: "UA", dial: "+380", flag: "🇺🇦", en: "Ukraine", ar: "أوكرانيا" },
  { code: "AE", dial: "+971", flag: "🇦🇪", en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
  { code: "GB", dial: "+44", flag: "🇬🇧", en: "United Kingdom", ar: "المملكة المتحدة" },
  { code: "US", dial: "+1", flag: "🇺🇸", en: "United States", ar: "الولايات المتحدة" },
  { code: "UY", dial: "+598", flag: "🇺🇾", en: "Uruguay", ar: "أورغواي" },
  { code: "UZ", dial: "+998", flag: "🇺🇿", en: "Uzbekistan", ar: "أوزبكستان" },
  { code: "VU", dial: "+678", flag: "🇻🇺", en: "Vanuatu", ar: "فانواتو" },
  { code: "VA", dial: "+379", flag: "🇻🇦", en: "Vatican City", ar: "الفاتيكان" },
  { code: "VE", dial: "+58", flag: "🇻🇪", en: "Venezuela", ar: "فنزويلا" },
  { code: "VN", dial: "+84", flag: "🇻🇳", en: "Vietnam", ar: "فيتنام" },
  { code: "YE", dial: "+967", flag: "🇾🇪", en: "Yemen", ar: "اليمن" },
  { code: "ZM", dial: "+260", flag: "🇿🇲", en: "Zambia", ar: "زامبيا" },
  { code: "ZW", dial: "+263", flag: "🇿🇼", en: "Zimbabwe", ar: "زيمبابوي" },
];

export const DEFAULT_COUNTRY =
  COUNTRIES.find((country) => country.code === "SD") ?? COUNTRIES[0]!;
