import { Link, useRouterState } from "@tanstack/react-router";
import { useState } from "react";
import { Check, Code2, ImageIcon, LayoutDashboard, LogOut, Menu, PanelLeftClose, PanelLeftOpen, Settings, X } from "lucide-react";
import { OperaLogoMark } from "@/components/brand/OperaLogoMark";
import { UserAvatar } from "@/components/profile/UserAvatar";
import { Button } from "@/components/ui/button";
import { useProfile } from "@/hooks/useProfile";
import { useAuth } from "@/hooks/useAuth";
import { useLang } from "@/lib/i18n";
import { useTheme } from "@/components/theme/ThemeProvider";
import { SIMPLE_THEMES } from "@/lib/themes";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

const links = [{ to: "/studio", icon: ImageIcon, en: "Creative Studio", ar: "استوديو الصور" }, { to: "/code", icon: Code2, en: "Code workspace", ar: "بيئة الأكواد" }, { to: "/dashboard", icon: LayoutDashboard, en: "Dashboard & profile", ar: "لوحة التحكم والملف" }] as const;
export function AppSidebar({ children }: { children: React.ReactNode }) {
  const { t, lang } = useLang(); const { username, displayName, avatarUrl } = useProfile(); const { logout } = useAuth(); const { palette, setPaletteId } = useTheme(); const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); const inChat = useRouterState({ select: s => s.location.pathname.startsWith("/chat") }); const name = displayName || username || "Your account";
  const sidebar = <aside className={`flex h-full flex-col border-e border-border bg-card transition-[width] duration-200 ${collapsed ? "md:w-20" : "md:w-72"} w-72`}><div className="flex h-16 items-center justify-between border-b border-border px-4"><Link to="/dashboard" className="flex min-w-0 items-center gap-3" onClick={() => setMobileOpen(false)}><OperaLogoMark className="h-9 w-9" />{!collapsed && <span className="truncate font-display text-base font-bold">Smart <span className="text-primary">Notes</span></span>}</Link><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setMobileOpen(false)}><X /></Button></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{links.map(item => <Link key={item.to} to={item.to} onClick={() => setMobileOpen(false)} activeProps={{ className: "bg-primary/12 text-primary" }} className="flex h-11 items-center gap-3 rounded-lg px-3 text-sm font-medium hover:bg-muted"><item.icon className="h-5 w-5 shrink-0" />{!collapsed && <span>{t(item.en, item.ar)}</span>}</Link>)}</nav><div className="border-t border-border p-3"><div className={`flex items-center gap-3 rounded-lg bg-muted/50 p-2 ${collapsed ? "justify-center" : ""}`}><UserAvatar src={avatarUrl} name={name} className="h-10 w-10 shrink-0" />{!collapsed && <div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{name}</p>{username && <p className="truncate text-xs text-muted-foreground">@{username}</p>}</div>}</div><div className="mt-2 flex items-center gap-1"><Button variant="ghost" className="min-w-0 flex-1" onClick={() => setCollapsed(v => !v)}>{collapsed ? <PanelLeftOpen /> : <><PanelLeftClose /><span>Collapse</span></>}</Button><Button variant="ghost" size="icon" onClick={() => void logout()} title="Sign out"><LogOut className="h-4 w-4" /></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><Settings /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-44">{SIMPLE_THEMES.map(theme => <DropdownMenuItem key={theme.id} onSelect={() => setPaletteId(theme.paletteId)}><span className={`theme-dot theme-dot-${theme.id}`} /><span className="flex-1">{t(theme.label, theme.labelAr)}</span>{palette.id === theme.paletteId && <Check className="h-4 w-4" />}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></div></aside>;
  return <div dir={lang === "ar" ? "rtl" : "ltr"} className="flex h-dvh overflow-hidden bg-background">{mobileOpen && <button type="button" className="fixed inset-0 z-40 bg-background/75 md:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu" />}<div className={`fixed inset-y-0 z-50 md:static md:translate-x-0 ${lang === "ar" ? "right-0" : "left-0"} ${mobileOpen ? "translate-x-0" : lang === "ar" ? "translate-x-full" : "-translate-x-full"} transition-transform`}>{sidebar}</div><div className="flex min-w-0 flex-1 flex-col overflow-hidden"><header className="flex h-16 shrink-0 items-center justify-between px-3 md:hidden"><Button variant="ghost" size="icon" onClick={() => setMobileOpen(true)}><Menu /></Button>{inChat && <span className="text-sm font-semibold">Smart Note AI</span>}<span /></header><main className="min-h-0 flex-1 overflow-auto">{children}</main></div></div>;
}
