import { Link } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Camera, Code2, ImageIcon, Loader2, MessageSquare, Save, Sparkles } from "lucide-react";
import { OperaLogoMark } from "@/components/brand/OperaLogoMark";
import { listImages, listThreads, saveLocalProfile } from "@/lib/local-db";
import { useProfile } from "@/hooks/useProfile";
import { UserAvatar } from "@/components/profile/UserAvatar";
import { uploadAvatar } from "@/lib/avatar";
import { useLang } from "@/lib/i18n";
import { NotesWorkspace } from "@/components/notes/NotesWorkspace";

export const Route = createFileRoute("/_authenticated/dashboard")({ head: () => ({ meta: [{ title: "Your workspace — Smart Note AI" }, { name: "description", content: "Manage your profile, notes and creative workspace." }] }), component: Dashboard });
function Dashboard() {
  const { t, lang, setLang } = useLang(); const queryClient = useQueryClient(); const [displayName, setDisplayName] = useState(""); const [username, setUsername] = useState(""); const [saving, setSaving] = useState(false); const { profile, avatarUrl, isLoading, refetch } = useProfile(); const fileInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (profile) { setDisplayName(profile.display_name ?? ""); setUsername(profile.username ?? ""); } }, [profile]);
  const changeAvatar = async (file: File) => { setSaving(true); const result = await uploadAvatar(file); if (!result.ok) { toast.error(result.message ?? "Upload failed"); setSaving(false); return; } saveLocalProfile({ avatar_url: result.path }); setSaving(false); await refetch(); toast.success("Picture updated"); };
  const save = () => { setSaving(true); saveLocalProfile({ display_name: displayName.trim(), username: username.trim() }); setSaving(false); toast.success("Profile saved"); void queryClient.invalidateQueries({ queryKey: ["profile"] }); };
  return <div dir={lang === "ar" ? "rtl" : "ltr"} className="min-h-full px-4 py-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-3"><Link to="/" className="flex items-center gap-3"><OperaLogoMark className="h-10 w-10" /><span className="font-display text-lg font-bold">Smart<span className="text-primary">Notes</span></span></Link><button type="button" onClick={() => setLang(lang === "ar" ? "en" : "ar")} className="btn-ghost !px-3 !py-2 text-xs">{lang === "ar" ? "English" : "العربية"}</button></header>
    <div className="mt-8 grid gap-6 lg:grid-cols-[0.85fr_1.15fr]"><section className="glass-strong rounded-2xl p-6"><div className="flex items-center gap-4"><button type="button" onClick={() => fileInputRef.current?.click()} className="relative"><UserAvatar src={avatarUrl} name={profile?.display_name ?? ""} className="h-16 w-16 text-lg" /><span className="absolute -bottom-1 -end-1 rounded-full bg-primary p-1.5 text-primary-foreground"><Camera className="h-3 w-3" /></span></button><input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={e => { const file = e.target.files?.[0]; e.target.value = ""; if (file) void changeAvatar(file); }} /><div><h1 className="text-2xl font-bold">{t("Welcome", "أهلاً")}, {profile?.display_name || t("friend", "صديقنا")}</h1><p className="text-sm text-muted-foreground">Your private command center.</p></div></div>{isLoading ? <Loader2 className="mx-auto mt-8 animate-spin text-primary" /> : <div className="mt-7 grid gap-3"><input value={displayName} onChange={e => setDisplayName(e.target.value)} placeholder="Display name" className="rounded-xl border bg-background/40 px-3.5 py-3 text-sm outline-none focus:border-primary" /><input value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" className="rounded-xl border bg-background/40 px-3.5 py-3 text-sm outline-none focus:border-primary" /><button type="button" onClick={save} disabled={saving} className="btn-hero justify-center disabled:opacity-60"><Save className="h-4 w-4" />Save changes</button></div>}</section><div className="grid gap-4 sm:grid-cols-2"><div className="glass rounded-2xl p-5"><MessageSquare className="text-primary" /><p className="mt-4 text-3xl font-bold">{listThreads().length}</p><p className="text-sm text-muted-foreground">Saved conversations</p></div><div className="glass rounded-2xl p-5"><ImageIcon className="text-primary" /><p className="mt-4 text-3xl font-bold">{listImages().length}</p><p className="text-sm text-muted-foreground">Generated images</p></div><Link to="/chat" className="glass rounded-2xl p-5 transition hover:border-primary/50"><Sparkles className="text-primary" /><p className="mt-4 font-semibold">Chat workspace</p><p className="text-sm text-muted-foreground">Think with an intelligent assistant.</p></Link><Link to="/code" className="glass rounded-2xl p-5 transition hover:border-primary/50"><Code2 className="text-primary" /><p className="mt-4 font-semibold">Code workspace</p><p className="text-sm text-muted-foreground">Build and refine ideas faster.</p></Link></div></div>
    <NotesWorkspace />
  </div></div>;
}
