/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedChatRouteRouteImport } from './routes/_authenticated/chat/route'
import { Route as AuthenticatedCodeRouteImport } from './routes/_authenticated/code'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCodeAssistRouteImport } from './routes/api/code-assist'
import { Route as ApiEditImageRouteImport } from './routes/api/edit-image'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat/$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRouteRoute = AuthenticatedChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodeRoute = AuthenticatedCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeAssistRoute = ApiCodeAssistRouteImport.update({
  id: '/api/code-assist',
  path: '/api/code-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditImageRoute = ApiEditImageRouteImport.update({
  id: '/api/edit-image',
  path: '/api/edit-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof AuthenticatedChatRouteRouteWithChildren
  '/code': typeof AuthenticatedCodeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/code-assist': typeof ApiCodeAssistRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof AuthenticatedCodeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/code-assist': typeof ApiCodeAssistRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRouteRouteWithChildren
  '/_authenticated/code': typeof AuthenticatedCodeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/code-assist': typeof ApiCodeAssistRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/code'
    | '/dashboard'
    | '/studio'
    | '/api/chat'
    | '/api/code-assist'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/transcribe'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/dashboard'
    | '/studio'
    | '/api/chat'
    | '/api/code-assist'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/transcribe'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/chat'
    | '/_authenticated/code'
    | '/_authenticated/dashboard'
    | '/_authenticated/studio'
    | '/api/chat'
    | '/api/code-assist'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/transcribe'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiCodeAssistRoute: typeof ApiCodeAssistRoute
  ApiEditImageRoute: typeof ApiEditImageRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/code': {
      id: '/_authenticated/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AuthenticatedCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-assist': {
      id: '/api/code-assist'
      path: '/api/code-assist'
      fullPath: '/api/code-assist'
      preLoaderRoute: typeof ApiCodeAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit-image': {
      id: '/api/edit-image'
      path: '/api/edit-image'
      fullPath: '/api/edit-image'
      preLoaderRoute: typeof ApiEditImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRouteRoute
    }
  }
}

interface AuthenticatedChatRouteRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteRouteChildren: AuthenticatedChatRouteRouteChildren =
  {
    AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
    AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  }

const AuthenticatedChatRouteRouteWithChildren =
  AuthenticatedChatRouteRoute._addFileChildren(
    AuthenticatedChatRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRouteRoute: typeof AuthenticatedChatRouteRouteWithChildren
  AuthenticatedCodeRoute: typeof AuthenticatedCodeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRouteRoute: AuthenticatedChatRouteRouteWithChildren,
  AuthenticatedCodeRoute: AuthenticatedCodeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiCodeAssistRoute: ApiCodeAssistRoute,
  ApiEditImageRoute: ApiEditImageRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
